version: 2

jobs:
  test_opa:
    machine:
      image: ubuntu-2004
    steps:
      - checkout
      - run:
          name: run opa tests
          command: docker run -v $(pwd)/resources/policies:/tmp/foobar openpolicyagent/opa:0.15.1 test /tmp/foobar

workflows:
  version: 2
  opatest:
    jobs:
      - test_opa
