on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  go-tests:
    name: Run Terratest Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.x
          terraform_wrapper: false

      - name: Download Go Modules
        working-directory: test
        run: go mod download

      - name: Set up Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          image: "kindest/node:v1.20.2@sha256:15d3b5c4f521a84896ed1ead1b14e4774d02202d5c65ab68f30eeaf310a3b1a7"

      - name: Quick test
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system

      - name: Run Go Tests
        working-directory: test
        run: |
          kind get kubeconfig > ./kubeconfig
          export KUBE_CONFIG_PATH="$PWD/kubeconfig"
          go test -v
