on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  go-tests:
    name: Run Terratest Unit Tests
    runs-on: ubuntu-latest
    # This is not needed now but it will for integration tests
    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.x
          terraform_wrapper: false

      - name: Download Go Modules
        working-directory: test
        run: go mod download

      - uses: engineerd/setup-kind@v0.5.0
      - name: Set up Kind for module testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)

      - name: Run Go Tests
        working-directory: test
        run: |
          kind get kubeconfig > ./kubeconfig
          export KUBE_CONFIG_PATH="$PWD/kubeconfig"
          go test -v
