on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  go-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.x
          terraform_wrapper: false

      - name: Run OPA tests
        working-directory: resources/policies
        run: |
          curl -L -o opa "https://openpolicyagent.org/downloads/v0.38.1/opa_linux_amd64_static"
          chmod +x ./opa
          ./opa test .

      - name: Run tf Tests
        working-directory: test/unit-test
        run: |
          terraform init
          terraform validate
